import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#226e63",
        "background": "#f7f9fc",
        "on-tertiary-container": "#005249",
        "secondary-fixed-dim": "#8cd4c7",
        "tertiary-fixed": "#8ff4e3",
        "surface-container-high": "#e6e8eb",
        "on-tertiary-fixed-variant": "#005047",
        "on-primary-fixed-variant": "#005322",
        "outline-variant": "#bbcbb9",
        "error": "#ba1a1a",
        "surface-container": "#eceef1",
        "tertiary-fixed-dim": "#72d8c8",
        "tertiary-container": "#63c9b9",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#005047",
        "primary-fixed": "#66ff8e",
        "surface-container-low": "#f2f4f7",
        "on-background": "#191c1e",
        "on-tertiary-fixed": "#00201c",
        "primary-container": "#25d366",
        "on-primary": "#ffffff",
        "surface": "#f7f9fc",
        "surface-tint": "#006d2f",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#3c4a3d",
        "surface-dim": "#d8dadd",
        "surface-container-highest": "#e0e3e6",
        "secondary": "#1c695f",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1e",
        "secondary-fixed": "#a8f0e3",
        "primary-fixed-dim": "#3de273",
        "surface-bright": "#f7f9fc",
        "inverse-on-surface": "#eff1f4",
        "outline": "#6c7b6b",
        "tertiary": "#006b5f",
        "primary": "#006d2f",
        "on-error": "#ffffff",
        "on-primary-fixed": "#002109",
        "secondary-container": "#a5ede0",
        "inverse-surface": "#2d3133",
        "inverse-primary": "#3de273",
        "surface-variant": "#e0e3e6",
        "on-primary-container": "#005523",
        "on-secondary-fixed": "#00201c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "content-min-width": "400px",
        "stack-xs": "0.25rem",
        "sidebar-width": "30%",
        "margin-base": "1.5rem",
        "stack-sm": "0.5rem",
        "gutter": "1rem",
        "stack-md": "1rem",
      },
      fontFamily: {
        "headline-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
